- name: variables at task level
  hosts: localhost
  #play level is parent
  vars:
  - money: "10000 RS"
    land: "100 hectors"
  tasks:
  - name: inherit values from play
    ansible.builtin.debug:
      msg: "MONEY: {{money}}, LAND: {{land}}"
  - name: inherit values from play and add and override
    vars:
    - money: "200000 RS"
      houses: "3 houses"
    ansible.builtin.debug: #it will take values in task level only bcz task is child and play is parent.task inherits the values from play
      msg: "MONEY: {{money}}, LAND: {{land}}, HOUSES: {{houses}}"