- name: Install packages
  hosts: localhost
  tasks:
  - name: Install package
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix
    - cyrus-sasl-plain
    - mailx