- name: install and remove packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install and remove package
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'absent'}
    - {name: 'mailx', state: 'installed'}